services:
  postgres:
    # container_name: postgres
    image: postgres:17
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      retries: 5
      start_period: 30s
      timeout: 10s
    restart: always
    volumes:
      - pgData:/var/lib/postgresql/data
      # this mounted directory contains a script that will create the databases and then a script that
      # will populate each database with tables and do other initialization tasks. They will run sequentially
      # in alphabetical order
      - ./init_scripts:/docker-entrypoint-initdb.d
      # mount the create tables files for the services that use postgres so they can be run by the script
      # that initializes the tables
      - ./user_service/internal/repository/sqlc/sql/schema.sql:/app-sql/user_service_init.sql:ro
      - ./document_service/internal/repository/sqlc/sql/schema.sql:/app-sql/document_service_init.sql:ro
  
  pgadmin:
    # container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=example@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - "5050:80"
    restart: always
  
  user-service:
    container_name: user-service
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=user_service
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
    ports:
      - "50051:50051"
    build:
      context: ./user_service
      dockerfile: Dockerfile
      target: runner
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
  
  document-service:
    container_name: document-service
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=document_service
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    build:
      context: ./document_service
      dockerfile: Dockerfile
      target: runner
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
  
  # Tempo runs as user 10001, and docker compose creates the volume as root.
  # As such, we need to chown the volume in order for Tempo to start correctly.
  init:
    image: &tempoImage grafana/tempo:latest
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - tempoData:/var/tempo

  tempo:
    image: *tempoImage
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - tempoData:/var/tempo
    ports:
      - "3200:3200" # tempo
      - "4317:4317" # otlp grpc
    depends_on:
      - init
  
  otel-collector:
    image: otel/opentelemetry-collector:0.86.0
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./otel_collector/otel-collector.yaml:/etc/otel-collector.yaml
    depends_on:
      - tempo
  
  grafana:
    image: grafana/grafana:11.0.0
    volumes:
      - ./grafana/datasources/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
      - GF_LOG_LEVEL=warn 
    ports:
      - "3000:3000"

volumes:
  pgData:
  tempoData: